[package]
name = "narrowway"
version = "0.1.0"
edition = "2021"
authors = ["31core <31core@tutanota.com>"]
license = "MIT"

[profile.release]
opt-level = 3

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
poc = []

[dependencies]
